### ISSUE TITLE
Add svg usgs watermark to the viz (S)

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#100]
make sure the watermark links out to usgs.gov

See previous visualizations for examples. paths are https://github.com/USGS-VIZLAB/hurricane-irma/blob/61c79532b9dc1c0b5f3f720f7b3a6d47ce794cfb/scripts/visualize/visualize.hurricane_map.R#L143

**Comment by aappling-usgs** [comment]
This is done, right? In #122? Looks like about 4.5 hours from Laura.
