### ISSUE TITLE
Plot of state water use rankings for key stories

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#115]
* MVP: static plot of states ranked by water use
* Nice to have 1a interactive: the static rank plot lets you mouse over each state for info
* Nice to have 1b interactive: 48 of the states/territories are sorted according to water use, try to figure out where the last three should land (drag and drop into position)

**Comment by jread-usgs** [comment]
Prototype for 1b (based on data for `total`, although probably more interesting for specific categories?):
![state_rank_plot](https://user-images.githubusercontent.com/2349007/38311423-c6964a8e-37e4-11e8-926b-021d9199d716.png)

Working on prototype for 1a and MVP

**Comment by jread-usgs** [comment]
prototype for 1a: 
![state_rank_plot1a](https://user-images.githubusercontent.com/2349007/38312965-9e35854c-37e8-11e8-8173-1da20d131e57.png)

**Comment by jread-usgs** [comment]
@aappling-usgs should we put an MVP version in the viz?

**Comment by aappling-usgs** [comment]
I think that would be good.

**Comment by aappling-usgs** [comment]
Stacked bar charts make it harder to compare individual categories, but they also take up less space and are probably perfectly adequate for this application - I'm good with that choice if you are.

And from there, if you're happy with this plan for an MVP, let's do it.

**Comment by jread-usgs** [comment]
I don't know, I am kind of he-hawing over this once I see the data as different charts. Seems the spatial component of the ranking for the top two components is what is interesting about this key story. 

Here is a quick MVP example for thermo and irrigation w/ the map. I struggled to see what the public would get from it w/o the map, but maybe I am missing the text context for this one. 

![state_rank_plot1a](https://user-images.githubusercontent.com/2349007/38335923-b3ceb92c-3825-11e8-860b-010aef6ec8fb.png)
![state_rank_plot1a_therm](https://user-images.githubusercontent.com/2349007/38335924-b3e29ab4-3825-11e8-8df4-3f4760400544.png)

**Comment by aappling-usgs** [comment]
So are you proposing 5 of these? Or interactive switching among categories?

The map story is certainly interesting but is not the only story. I think viewers faced with just a bar plot would first look for their state, second look at the top few states, and third look at the bottom few. The names of states, and what they remember of travelling through or who they know who lives in each state, will also be interesting to viewers.

**Comment by aappling-usgs** [comment]
We will have already told the thermo vs irrigation story above, so if you're not excited about what's left, another option is to leave out the state figure altogether.

**Comment by ldecicco-USGS** [comment]
Could you do the states ordered west to east, and stack thermo and irrigation? It might look cool, it might not....when I'm doing my prototype on the scatter plots, maybe I'll give it a shot

**Comment by ldecicco-USGS** [comment]
Nevermind, looks like water use already does that in it's circular

**Comment by jread-usgs** [comment]
calling this done and moving on to #186
