### ISSUE TITLE
Use multi-circle svg path for each water use category

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#119]
Generate paths something like https://github.com/USGS-VIZLAB/water-use-15/pull/118/files#r178587103, but we just need one final path per category

At least for the time being (unless and until we do #25), do this in javascript using the existing centroid data and `projection()`. There are handy functions like `Array.prototype.join()` that should help.

Then draw circles using these paths rather than by drawing each circle separately.

**Comment by aappling-usgs** [comment]
One thing we give up when we do this is the ability to change the aesthetics of a single circle to show that it's being highlights. As part of this task, let's also add a single circle that's the "highlight" circle that can be resized and recolored each time a county is hovered over, to emphasize the circle that is relevant to that county.

**Comment by aappling-usgs** [comment]
This issue blocks #96, so put a message in there when this one is ready.

**Comment by aappling-usgs** [comment]
Now it blocks not #96 but #154, and then it's only actually a blocker if we decide that we're going to finish this issue (#119) before Friday.

**Comment by aappling-usgs** [comment]
Looking at master vs my branch for this issue so far. Load times have more to do with the data adjustments I've done than with the circles as circles vs paths, but they're part of my current PR and I'm curious.

Loads from master:
1455 scripting, 654 rendering, 42 painting
1520 scripting, 589 rendering, 37 painting
1509 scripting, 622 rendering, 44 painting

Loads from circle-paths branch:
1017 scripting, 450 rendering, 64 painting
1034 scripting, 454 rendering, 60 painting
1019 scripting, 442 rendering, 67 painting

**Comment by aappling-usgs** [comment]
Teverted paths back to circles in 5be5bc0, with goal of just keeping the load time improvements for now.  Then I checked that the improvements still exist after changing the way we represent circles (spoiler - they don't!):

Loads from circle-paths branch after 5be5bc0:
1581 scripting, 632 rendering, 44 painting
1484 scripting, 631 rendering, 44 painting
1553 scripting, 640 rendering, 42 painting

Loads from circle-paths branch with commenting out circles as circles, bringing back circles as paths:
1046 scripting, 402 rendering, 128 painting
1055 scripting, 221 rendering, 127 painting
1060 scripting, 318 rendering, 291 painting

And master again:
1533 scripting, 622 rendering, 42 painting
1563 scripting, 682 rendering, 43 painting
1460 scripting, 593 rendering, 38 painting

I guess it's the data preparation rather than the data size that is actually getting us!

Here's what I had thought was driving the page load improvement - I did make a couple of files smaller. Here's the data when built from master:
![image](https://user-images.githubusercontent.com/12039957/38518088-d9e1926e-3bf0-11e8-827c-6989dacdc3b4.png)

and here when built from circle-paths:
![image](https://user-images.githubusercontent.com/12039957/38517757-d19aaa10-3bef-11e8-9049-f8742f6cba4c.png)

So the data files are indeed smaller, but they don't matter nearly as much as I thought. Nothing like some data to enforce some humility :blush: !

**Comment by aappling-usgs** [comment]
OK, pushing this issue to a later date because there other higher priority issues for this week. #148 gets us a lot closer, but with the sporadic rendering issues identified in that PR, we'll be leaving circles-as-paths commented out for now.

**Comment by aappling-usgs** [comment]
Reopened because it still doesn't work consistently on my computer. I think we need more tests on dev and/or beta, with multiple computers, before we can make a final call.

**Comment by lindsaycarr** [comment]
Ugh, so I can see paths on my desktop computer on beta, but not phone.

**Comment by aappling-usgs** [comment]
And I'm still missing some paths on dev and beta on my computer. =(

**Comment by aappling-usgs** [comment]
Might be closer! I can see Total at the national scale now. Still losing it when I zoom in to a state, though.

**Comment by aappling-usgs** [comment]
Oh, but just realized I was testing without having merged the above PR. Merged now, will test again shortly...

**Comment by aappling-usgs** [comment]
Ooooooh it's working on chrome! getting on the plane now. We should probably test on a few more devices, but this is big!

**Comment by aappling-usgs** [comment]
Hmm- now I can see some but not all of the dots at a time. Could it be that only one of the two paths is working? 
![180429-missing-circles](https://user-images.githubusercontent.com/12039957/39408321-5235b450-4b89-11e8-8188-7b09c3e802dd.gif)
Looks like which counties are missing stays consistent across categories:
![180429-consistently-missing](https://user-images.githubusercontent.com/12039957/39408395-70065362-4b8a-11e8-8a4f-d46b89983902.gif)

**Comment by aappling-usgs** [comment]
I'm getting similar behavior on my android phone.

**Comment by lindsaycarr** [comment]
Oof I just saw these comments....I can explore more while traveling tomorrow.

**Comment by jread-usgs** [comment]
Is this done? can it be closed?

**Comment by lindsaycarr** [comment]
Yes, I think it is good to go!
