### ISSUE TITLE
Inject text for key stories

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#133]
I think that even our current draft text would be useful to see on the page

**Comment by ldecicco-USGS** [comment]
@aappling-usgs want me to go ahead on this?...it looks like the text in the Google Doc is still in flux. I can...just double-checking

**Comment by aappling-usgs** [comment]
Yes, please do. I know it's still in flux, but I think having most of the text in there will help us to see how the stories are shaping up visually. Just copy in something that seems approximately like where we're headed. I'm sure there will be a round or two of revisions of this text later, but I think it'll be worth it to have previews along the way.

**Comment by aappling-usgs** [comment]
We'll need revisions, but #141 is everything I was hoping for this time around. @ldecicco-USGS , what's your final time estimate?

**Comment by ldecicco-USGS** [comment]
3 hours
