### ISSUE TITLE
Implement new category selector/legends (M)

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#139]
This task is to change the buttons:
 - The selected button will expand to the right and all other buttons will change to a neutral grey
 - the selected button will contain "{view_selection}.XX" for the time being (XX filled in for another task). `view_selection` is `us`, `st`, `cty` as a placeholder to make sure we are aware the data will change with each selection. 
 - In desktop, the buttons will be on the left side of the map
 - Desktop will have a title for the categories which will adjust based on the selection (no title for mobile)
 - Mostly opaque backing rectangle for the desktop view
 - in mobile, the buttons will be under the map
 - Am assuming we want the buttons to be integrated within the svg, not outside of it (current implementation)
 - This does not include the drop down selector tasks
 - Note for desktop, this change likely impacts the math behind our state zoom, since we won't want the category/legend to sit on part of the active state. Dealing w/ this issue is outside of the scope of this task. 

See mobile here: 
![image](https://user-images.githubusercontent.com/2349007/38381709-401be4c0-38cd-11e8-8cba-ad561e584b58.png)
and desktop here:
https://github.com/USGS-VIZLAB/water-use-15/issues/89#issuecomment-378579693

**Comment by jread-usgs** [comment]
I didn’t think we were planning to have the county drop down or the zoom out visible at the national scale. We’ve got some white space above Maine we can ditch and can always move the social icons to appear at the bottom on the viz.

**Comment by mwernimont** [comment]
We aren't. It'll be fixed with future PR's of functionality for the mobile UI.

**Comment by lindsaycarr** [comment]
To answer your question about buttons, I think we could shorten the drop downs a bit and make sure everything is visible. I think they might fit, but we won't be able to see the text. We know we want them on there somewhere, so we can get them up and then play around with the layout after.

**Comment by lindsaycarr** [comment]
I'll let @aappling-usgs decide if we should close this issue and make a new issue for the problem mentioned here https://github.com/USGS-VIZLAB/water-use-15/pull/177#issuecomment-380883461, or if we should just keep this one open until it is addressed.

**Comment by aappling-usgs** [comment]
As noted in #177, I believe that issue is captured in #160.
