### ISSUE TITLE
Determine key user-specific analytics tracking beyond simple interactions

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#143]
We'll want to generate a list of things that will be important in telling the story of how this viz did, and also important in helping us determine how useful certain features are. After generating this list, we'll probably want to turn to figuring out implementation details. Things that come to mind:

 - did a user look at industrial (at all. true or false)
 - did a user zoom to any state

This would all us to say things like "14% of visitors to the site looked at the industrial category", and "20% of users took a closer look at a state-specific view"

and more. Just seeding this issue with two sample ideas. We might want to balance the value they would add to our analytics story vs how challenging or disruptive their implementation might be.

**Comment by wdwatkins** [comment]
Based on our standup discussion, my thoughts are that we can keep a count of how many times a user has done a particular category of action — i.e. , within `updateView`, `updateCategory`, etc, so then we can just look at "first actions" for each action to see what % of sessions did them.  This would be more complicated to do for individual categories for your first example, but I think would still be doable?

Other implementation ideas?

**Comment by jread-usgs** [comment]
We'll want to include something in here with the "rank-em" state guesses. Need to know what percentage of users tried the game, and what the wrong/right answers were. E.g., wrong = MI went into OK slot.

**Comment by aappling-usgs** [comment]
Yes, so excited about analytics for rank-em! That was my favorite part of the fish viz analytics.

**Comment by wdwatkins** [comment]
#303 records where states were dropped (no drops at all would indicate not trying the game).

**Comment by lindsaycarr** [comment]
Decided at standup today to not add events for when people hover on bars in the rank-em figure. David and I weren't sure how much additional information that would provide and there is a limit to how many events GA will track on this free account.
