### ISSUE TITLE
Analytics - Scroll depth tracking for key stories

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#146]
We'd like to know how far down a user scrolls before leaving page, with "how far down" pegged to which key story or text section is the last one visible

**Comment by wdwatkins** [comment]
Did we ever come to a conclusion on whether this is doable without parallax like on the fish viz?

**Comment by jread-usgs** [comment]
yes, it does seems doable as the fish viz didn't take advantage of parallax features to do this. Instead if was checking for certain elements being above or within the window view. It made these checks 4 times a second.

**Comment by wdwatkins** [comment]
Looks like we need to add hashes for the sections below the map

**Comment by wdwatkins** [comment]
fish viz implementation is here: https://github.com/USGS-VIZLAB/climate-fish-habitat/blob/fedab7226d889bb0bac202da36a3b0c42986a95e/layout/js/app.js#L51

**Comment by lindsaycarr** [comment]
☝️ would that be very hard to implement? We already have some hashes, and could add some more to `wu_story.mustache` as needed. We've already got `#wu-story`, `#national-pie`, `#national-static-pie`, `#rank-states-interactive`, `#data-collection`, and a few in the footer.

**Comment by wdwatkins** [comment]
I'm going to give it a shot, hopefully we can just reuse the code used ☝️ .  But I really don't know, this is kinda beyond my javscript skillz.

**Comment by wdwatkins** [comment]
Seems this involves adding `jquery`, is that a problem?

**Comment by jread-usgs** [comment]
yeah, I think jquery is a little hefty to bring in for this alone. We might want to ping a js expert to see if this is doable easily w/ vanilla js
