### ISSUE TITLE
Static pie chart for whole nation

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#150]
For key stories intro. One big pie chart for whole US at once. 5 slices, one pie, svg.

**Comment by lindsaycarr** [comment]
So far ... 

![image](https://user-images.githubusercontent.com/13220910/38518923-ebb94d02-3c03-11e8-9764-bc979cd3e22d.png)

Do we want hovers, text, nothing to indicate categories?

**Comment by aappling-usgs** [comment]
Slick! We'll need some way to explain `other` at a minimum. I think I'd lean toward text callouts so the user doesn't NEED to hover to get the info...though 4 of the 5 categories are labeled just above...

**Comment by lindsaycarr** [comment]
I'm playing with text now and will show how that looks

**Comment by lindsaycarr** [comment]
@aappling-usgs 

![image](https://user-images.githubusercontent.com/13220910/38522241-91e4d2ec-3c0d-11e8-8aba-b9fa6e9483f4.png)

**Comment by aappling-usgs** [comment]
Not bad. How does it look with Irrigation and Thermoelectric placed within their pie slices?

**Comment by aappling-usgs** [comment]
Got an hours estimate for this one, @lindsaycarr ?

**Comment by lindsaycarr** [comment]
3 hrs
