### ISSUE TITLE
508 compliance - initial check

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#152]
Run it through a checker. Start by seeing if there are any easy fixes.

**Comment by wdwatkins** [comment]
- [ ] https://beta-owi.usgs.gov/vizlab/water-use-15/#view=USA&category=total
       Line 1 3 520 541
- [ ] Provide a way to skip repetitive navigation links.  Without skip links, keyboard users must tab through the navigation links to get to page content. Headings and landmarks allow screen reader users to skip navigation, but don't work for other keyboard users. Add a "Skip to Content" link at the start of the document hidden offscreen by CSS, and made visible on focus, so it's available to keyboard and screen reader users: <a class="accessible" href="#main">[Skip to Content]</a>

- [ ]  This page has markup errors, causing screen readers to miss content.
https://beta-owi.usgs.gov/vizlab/water-use-15/ | Line 166 169 171 530 535 |  
  | https://beta-owi.usgs.gov/vizlab/water-use-15/embed-water-use-15.html | Line 141 160 162 |

**Comment by wdwatkins** [comment]
- [ ] No meta description tag found. Use a description tag that accurately describes the contents
- [ ] This page has no H1 element, which violates Bing webmaster guidelines.
- [ ] Offer an HTML site map to your users with links that point to the important parts of your site. (not sure this makes sense for us)
- [ ] Omitting IMG WIDTH or HEIGHT attributes means page text jumps about as images load.
Line 180 201 215 229 243 ...

**Comment by wdwatkins** [comment]
some markup bugs:
![image](https://user-images.githubusercontent.com/13987349/38513183-019ae0d8-3bf3-11e8-9001-b9e3bb60f039.png)
![image](https://user-images.githubusercontent.com/13987349/38513195-0b89a1a6-3bf3-11e8-91c1-a61fd2a1f226.png)

**Comment by wdwatkins** [comment]
These page numbers seem to include expanding all the javascript elements.  https://validator.w3.org/ seems to be more useful for the markup stuff

**Comment by wdwatkins** [comment]
@aappling-usgs I can probably handle the alt tags, but won't be very efficient on the other stuff since I am an html `<noob>`

**Comment by aappling-usgs** [comment]
Alt tags would be a good start :+1:

**Comment by wdwatkins** [comment]
aXe browser plugin seems much more user-friendly: https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

**Comment by aappling-usgs** [comment]
We can call this initial check done; alt tags are fixed, learned about some tools to run compliance checks, got a list of things that will need changing.  next step is #157.
