### ISSUE TITLE
Get a dev job up and running

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#16]
The Jenkins job should sync with the `dev-owi.usgs.gov-website` S3 bucket for now. It should be viewable at dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/vizlab/water-use-15

In a couple of weeks we will be switching to the S3 bucket named `dev-owi.usgs.gov`, but that has to wait on an RFC.

**Comment by lindsaycarr** [comment]
@wdwatkins this is done, right? How long did it take?

**Comment by wdwatkins** [comment]
Yes.  5 hours was probably about right, although it shouldn't normally take that long if we aren't introducing new system dependencies that have to be installed.
