### ISSUE TITLE
Revisit need for mouseover delays

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#160]
Could prevent accidental hovering (e.g., when you're really just moving your mouse to another part of the screen). Alternatively, if transitions or quick, could be better to have immediate responsiveness after all. 

Spinoff from #126

**Comment by ldecicco-USGS** [comment]
So we're hoping this issue will fix the jumping up to the selected target. Increasing the delay could help, and other option might be to add an invisible box that eliminates the gaps between the colored boxes.

**Comment by aappling-usgs** [comment]
I'm going to unassign myself because I won't get to this today or tomorrow, but I'm happy to reassign myself if it still needs doing next week.
