### ISSUE TITLE
Finalize the key stories text

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#161]

**Comment by lindsaycarr** [comment]
Finalized text sent to Marty for #202 in a power point file (for placement). Also available below. I think this could be added the repo as a text/yaml file in whatever directory the figure code ends up in the repo via #200.

> 
> Aquaculture, mining, self-supplied domestic, and livestock water uses are distributed unevenly across the US. There are large withdrawals for aquaculture along the Snake River in southern Idaho.
> 
> Industrial withdrawals are driven by many factors. Industrial facilities for production of steel in Lake County, Indiana, are located on Lake Michigan, a large source of fresh water, with access to water and land transportation, and ore and coal deposits. Lake County accounts for 8% of the US industrial water withdrawals.
> 
> Thermoelectric power plants use steam to drive turbines and generate electricity. In the eastern U.S. where water is relatively abundant, large volumes of water often are withdrawn, used once for cooling, then returned to the source a little warmer than before. In the western U.S., cooling water is more often withdrawn and recirculated many times, so less is withdrawn overall.
> 
> The Gulf Coast is another hotspot of industrial withdrawals for the chemical and petroleum industries.
> 
> Larger withdrawals in Alaska in the “other” categories are for aquaculture and mining.
> 
> Irrigation occurs in most areas of the country, but is larger in areas where rainfall is insufficient to meet crop what needs, such as in the drier parts of the West. Irrigation in eastern Arkansas provides water to flood rice fields as well as supplement rainfall to other crops.
> 
> Public Supply water withdrawals, mostly for Domestic use, are highest in counties with large numbers of people.

**Comment by lindsaycarr** [comment]
This text was iterated on with NWULT. Finalized.
