### ISSUE TITLE
Adapt click behavior for mobile

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#162]
I think we're looking for these behaviors:
- [ ] from national view, tap on state zooms to state
- [ ] within state view, tap on county (county in selected state) gives county info
- [ ] within state view, tap on adjacent state pans to that state
- [ ] within state view, taps in the ocean/canada/mexico should still zoom you out
- no hover or pinch behaviors

**Comment by jread-usgs** [comment]
only edit I would add is that "within state view, tap on county (county in selected state) gives county info"

**Comment by aappling-usgs** [comment]
Adding this 
- [ ] within state view, taps in the ocean/canada/mexico should still zoom you out

**Comment by mwernimont** [comment]
Don't you think that will confuse people?  If that tap works why not tap on the states to zoom out?  My 2 cents is zoom-out button is the only option to zoom out on mobile.

**Comment by jread-usgs** [comment]
I like the idea of using the background rectangle as another place you can zoom out from, and don't think it costs us much to implement. It won't be relevant for many/most states, but will help for AK, HI, PR _if_ it doesn't cause people to unexpectedly zoom out when they are trying to tap on St Thomas, for example...

**Comment by aappling-usgs** [comment]
I believe we're already using the background rectangle in this way; just want to make sure we keep that behavior and are aware of it. You can try it out on dev and beta to see if it gets you what you want.
