### ISSUE TITLE
St Thomas county isn't in the zoom

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#179]
Only St Croix shows up:
![180411-st-thomas](https://user-images.githubusercontent.com/12039957/38648713-9abb526a-3da7-11e8-9187-a837b45094aa.gif)

**Comment by jread-usgs** [comment]
Noted in the style sweep too, but better to have its own issue

**Comment by aappling-usgs** [comment]
Oh, oops, wasn't thinking of that as a style sweep so didn't even look. I'll open up the style sweep issue before adding more issues.
