### ISSUE TITLE
Add links between clicks/taps and dropdown

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#180]
Currently most click/tap-based behaviors should but don't change what's visible in the drop down:
* zoom-taps to or from from national view
* pan-taps from state view to another state
These behaviors work (as specified in #162), they just don't change the dropdown.

**Comment by aappling-usgs** [comment]
![image](https://user-images.githubusercontent.com/12039957/38649045-4ac4cc08-3da9-11e8-8781-ed1bc94b6db4.png)

**Comment by lindsaycarr** [comment]
Just making a note - I think this issue should create helper functions for what is shown in the drop down. And the way to update what is currently selected in the dropdown is:

```
activeView = "HI";
d3.select(".view-select").property ("selected", activeView);
```

The `value` field for the option elements is set as the state abbreviation for the view selector and county GEOIDs for the county selector

**Comment by lindsaycarr** [comment]
@aappling-usgs I think this is done with #184.
