### ISSUE TITLE
Drop tooltips, add info in category legend

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#181]
See mockups at https://github.com/USGS-VIZLAB/water-use-15/issues/89#issuecomment-378579693 -- looking to get the state/county/nation name and the water use value into the legend. We can drop population.

Task predicted in #135:
* rounding/styling water use values shown in the category legend (e.g., 2.00000021)

Task worried about by me:
* will long county names overrun the button/legend box? we may need to make the box wider and/or rearrange the text so it fits. See Alaska for some extra-long county names.

**Comment by ldecicco-USGS** [comment]
Is this what we are talking about?

![image](https://user-images.githubusercontent.com/1105215/38892855-0bde8976-424e-11e8-9144-6ad3f62a6650.png)

**Comment by ldecicco-USGS** [comment]
Or I guess...when you click on a category...then hover over a county, just that category's legend lights up with a number for that county?

**Comment by aappling-usgs** [comment]
yes, I've been picturing that only the current category would get a number and a color; the other bars would stay gray and at their neutral lengths.

**Comment by ldecicco-USGS** [comment]
And just ploop the county name somewhere? At the bottom like that or up at the top with "2015 Wisconsin water use"

**Comment by aappling-usgs** [comment]
How about _instead_ of Wisconsin? and I've proposed (and implemented) not having "2015" in the legend title at all, to save space:
![image](https://user-images.githubusercontent.com/12039957/38893250-9aae068c-423e-11e8-999c-9951aefd5a45.png)

So for a single county, we could have

```
Water Use in Dane County, WI
(millions of gallons per day)
[ Total                 370 ]
[ Thermoelectric        ]
[ Public Supply         ]
[ Irrigation            ]
[ Industrial            ]
```

**Comment by aappling-usgs** [comment]
So I think the only changes to the legend for this issue are to use data to replace the XXX with `the U.S.` or a [state name] or a [county name, state abbv], then replace the XX with the mgal/d used for the active category at that spatial scale

**Comment by aappling-usgs** [comment]
After #194, the remaining tasks for this issue are to get national-level and state-level totals to be visible in the legend when no county is selected.

**Comment by ldecicco-USGS** [comment]
Ohhh, I hadn't thought of that. Probably want the legend title to change then too to "U.S. Water Use" and "Wisconsin Water Use"
