### ISSUE TITLE
Prototype using lo-res county boundaries in mobile

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#189]
Related to #188, which is to "only load hi-res county boundaries in mobile": What if we actually didn't even do that, but only ever loaded and used the LOW-res county boundaries in mobile, even on zoom? Maybe they'd be high enough resolution to pass even when zoomed in?

I think this idea is worth prototyping before we commit. On the one hand, it would be great if we could save some mobile users some data transfer by sticking to the low-res boundaries. On the other hand, I worry that the low-res boundaries will look too coarse even on mobile. Some screenshots (or better, people trying this out on mobile) would help us determine whether the low-res boundaries are passable on small screens.

Jordan notes that tablets are a weird intermediate space - might or might not count as mobile, but definitely show big enough screens that the low-res boundaries are a style risk. Keep these in mind.

**Comment by aappling-usgs** [comment]
Some low res vs high res contrasts:

Virgin Islands
low:
![image](https://user-images.githubusercontent.com/12039957/39222460-95d4d9fc-47f1-11e8-8574-f22e3c338770.png)
high:
![image](https://user-images.githubusercontent.com/12039957/39222656-af3acfe0-47f2-11e8-93c6-dc7695eeb901.png)

Texas
low:
![image](https://user-images.githubusercontent.com/12039957/39222473-a9f17fb2-47f1-11e8-914b-30e30a4d0f2a.png)
high:
![image](https://user-images.githubusercontent.com/12039957/39222647-9c85c968-47f2-11e8-888d-cf361f6398bf.png)

Massachusetts
low:
![image](https://user-images.githubusercontent.com/12039957/39222481-bcb7e9ec-47f1-11e8-832b-2885d8fb3b40.png)
high:
![image](https://user-images.githubusercontent.com/12039957/39222631-895c1748-47f2-11e8-917c-f2dc6bbd7484.png)

Wisconsin
low:
![image](https://user-images.githubusercontent.com/12039957/39222497-d1eee996-47f1-11e8-80ff-6e3faa5b51f9.png)
high:
![image](https://user-images.githubusercontent.com/12039957/39222611-704c3792-47f2-11e8-873d-8cd740e8a66e.png)

These are documented in commit bd1083b and then undone by the following commit 0ed88bc.

My take is that we could get away with low-res for many states, but small ones like MA and VI look a lot better at high resolution. We could conceivably customize the resolution if we switched to loading the county borders state by state, but that would require choosing to resolve the backlogged issue #237.

**Comment by aappling-usgs** [comment]
Options from here:
1. send this issue to the backlog to sit behind #237, maybe resolve them both some day; keep the high-res data in use
2. bring #237 into the main queue and plan to resolve them both soon
3. decide that the low-res data is actually fine for all states and reapply bd1083b

**Comment by jread-usgs** [comment]
Excellent overview. I don't know that I am caught up on the other issues, can you let me know how much (in % data volume?) that we save mobile users by sticking w/ the low res? 

It sure looks good for mobile in all of the screenshots except VI...

**Comment by jread-usgs** [comment]
I think my knee-jerk vote is to backlog this for now, but knowing we'd like to be able to do low-res on mobile in the future for re-use of this mapping concept. One potential solution in the future (unless I am misunderstanding it) is to do the GIS simplification _after_ scaling up/down the geometry to the viewing area. So this would mean PR/VI would look higher res but AK would look lower res.

**Comment by lindsaycarr** [comment]
I think low-res looks kind of strange for really any small state, so the entire Northeast. It would be nice to test out what kind of performance gains we get from low-res only on mobile. I tried loading beta on my device this morning on data and it was pretty slow.

**Comment by jread-usgs** [comment]
It looks a little strange, but I think it is a tradeoff in the future that we should likely take. IMO, the only unacceptable part about this lower res version for mobile is that one of the Virgin Islands disappears.

**Comment by aappling-usgs** [comment]
Thanks for the thoughts. I agree that most of the states look pretty good. The low-res county boundaries are 848 Kb and the hi-res county boundaries are 1.8 MB. We've just saved ourselves the 848 by only loading one version of the boundaries ever for mobile (open PR #236), not yet visible in beta, but we're still talking about 1 MB of flex room.

A third option is to create a medium-resolution version that shows the Virgin Islands but is coarser than our desktop hi-res version. Maybe we could get something that's more like 1.3 MB rather than 1.8?

Re: "do the GIS simplification after scaling up/down the geometry to the viewing area" - yes, I'd love to figure this out someday. As noted in https://github.com/USGS-VIZLAB/water-use-15/issues/237#issuecomment-384321384, one challenge we'll face there (probably overcomable, but will take some extra coding/thinking time) is that the state boundaries need to match the county boundaries, so simplifying each state's counties differently means we might need to package different versions of the state boundaries for various county resolutions.

**Comment by jread-usgs** [comment]
I am playing around with this on beta, and wonder if performance is maybe the bigger issue than data volume (but the two are related). My phone seems to suffer with the current zoom/pan functionality, but I am not sure how much of this is a result of higher res paths vs a more general snappiness issue on slower phones (I am using an older slower iPhone)

**Comment by aappling-usgs** [comment]
I share your suspicion that processing time is a big chunk of it now - larger file size leads to greater processing demands just because there's more to process, but even on desktop, even just transitioning between colors in the same map can be slowish, and #163 notes that firefox is extra painful. We're still asking a lot of the browser on every device, even after all we've done to try to ask less.

**Comment by aappling-usgs** [comment]
Next step: test *performance* differences between using low-res and high-res. If there are noticeable gains, then we proceed to #255.

**Comment by aappling-usgs** [comment]
Marty has compared performance and reports that low-res is noticeably faster to load, though not really faster on transitions.
