### ISSUE TITLE
Improve tooltip performance

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#19]
How can users access overlapped circles? Are there speed issues to be addressed? Do the tooltips always look their best?

**Comment by lindsaycarr** [comment]
Initial circle opacity is slowing this down. If CSS color definitions for circles had alpha built in, it might help.

**Comment by lindsaycarr** [comment]
Think about hover capability for tiny tiny circles that are inside larger circles. Can people successfully hover? See https://github.com/USGS-VIZLAB/water-use-15/pull/55#discussion_r171679881. Also, think about hovers on mobile...

**Comment by jread-usgs** [comment]
See references for profiling: https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference

[Current version](https://github.com/USGS-VIZLAB/water-use-15/pull/57) is maxing CPU whenever we move the mouse on a circle 
![image](https://user-images.githubusercontent.com/2349007/36904616-c277b4e0-1df6-11e8-863f-5ea12fff260d.png)

Very little CPU is used for anything other than Rastering

**Comment by jread-usgs** [comment]
Much more manageable w/ opaque circles (but that along isn't a solution for us):

![image](https://user-images.githubusercontent.com/2349007/36905128-237e85f6-1df8-11e8-94f3-690b755871a4.png)

**Comment by jread-usgs** [comment]
and it looks like @lindsaycarr is right, baking the alpha into the fill instead of opacity makes this run just as well as (or at least I couldn't tell the difference) 100% opaque:

![image](https://user-images.githubusercontent.com/2349007/36905250-88cca0a0-1df8-11e8-9350-68839bfbe545.png)

**Comment by aappling-usgs** [comment]
cool trick!

**Comment by aappling-usgs** [comment]
Where are the dots on the right edge in that example? you're not talking about the legend, are you?

**Comment by wdwatkins** [comment]
The thermoelectric circles to the east of Oregon.

**Comment by aappling-usgs** [comment]
Sounds like removing sorting and hovering on counties rather than dots is solving this sufficiently for us (done in #106). We can add a new issue later if we find that there's more to be done.
