### ISSUE TITLE
Detect mobile vs desktop better

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#190]
Detection goes in `resize()`, which I think should continue to work.

We're starting to make more assumptions that are more holistically relevant to mobile, rather than just having to do with screen/window size. See #188, for example. 

Therefore, I think we should decide whether we're in mobile mode based on whether the user is actually on a mobile device or not, rather than the current method of basing that decision on screen size.

There's some middle ground with tablets, which have mobile interactivity but larger screens, which may require special consideration. Do we need a `tablet` mode, too, or can these fit into `desktop` or `mobile` modes?

**Comment by lindsaycarr** [comment]
Slack convo to clarify this task

Alison:
> the main function of `resize()` is to move elements around the svg - that's not the part that you'd want to do differently, is it?
> the only part i think is relevant to #190 is https://github.com/USGS-VIZLAB/water-use-15/blob/master/js/resize.js#L3-L9

Lindsay:
> ah ha! OK that's the piece I feel we were missing. Literally improve the way we are determing "this is being viewed on a mobile device" and "this is being viewed on a desktop"

Alison:
> yeah, that's all. i was using window size but i think we shoudl make a clean split between actually-mobile and actually-desktop, even when somebody makes teh desktop window really small - you agree?
and then we need some plan for what to do with tablets - are they "mobile" mode so we can use tapping rather than clicking? or do we use separate mode designations to decide between tapping/clicking and legend on left/bottom?

Marty:
> Yeah we can do device specific media queries.  I'm sure I can go check out CSS tricks, as they probably have a treasure trove of device sizes and the media queries to specifically treat them differently

**Comment by aappling-usgs** [comment]
Resolved to MVP level in #240. what's left is to support hovering for laptops/desktops with tappable screens; otherwise this distinguishes well between mobile and desktop and between narrow and wide screens, which means that ipads look like desktop (layout) but act like mobile (tapping instead of hovering).
