### ISSUE TITLE
Improve user experience in the NE

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#197]
Jordan, on 4/11/18: Our user experience in the NE needs some work, but I am not sure I would call it a priority this week. It is really hard to see what county you are getting values from when zoomed in (for example) to New Jersey and looking at total or thermo. I don't know if there are simpler solutions, but my suggestion later on would be to use a use path for the county to create a copy of the county outline (no fill) that sits on top of everything and has a thin white-ish stroke.

This may be partly addressed by #196

**Comment by lindsaycarr** [comment]
I think this was fixed by scaling the circles on zoom. Now, none of the circles overlap and you can see counties.

![fix_ne](https://user-images.githubusercontent.com/13220910/39638256-46f1b7c8-4f8b-11e8-93bd-092af76dbb14.gif)
