### ISSUE TITLE
Explore key stories

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#20]
Think about how and whether to include key stories. (i love the general idea of key stories, just want us to also consider the costs of introducing additional figures and/or categories versus our recent discussion of focusing on a lightweight viz with really snappy look and performance)

From Nancy:
> we can do more brainstorming on the water-use side if there's a place for more input on stories to tell.  Things that come to mind:
> --contrasting irrigation which is very areal/geographic as your sample shows, vs thermoelectric which has large withdrawals in scattered counties where the plants are
> --consumptive use vs withdrawal for those 2 categories: CU for irrigation is usually a large percent of the withdrawal, but CU for thermoelectric can be very large or very small depending on the cooling system type at the plant(s) in that county 
> NWULT can come up with more…

**Comment by aappling-usgs** [comment]
1st step: generate ideas (talk with NWULT), possibly create some quick prototypes

**Comment by dblodgett-usgs** [comment]
Sent a note to Nancy -- cc'd @lindsaycarr and @aappling-usgs so you are up to date. Spent about 30 minutes so far.

**Comment by aappling-usgs** [comment]
Closing this one because we're moving into prototyping and implementing (#115, #114, #133). Depends on how you count, but I've spent maybe 5 hours on discussing key story ideas, figures, and text. @lindsaycarr and @jread-usgs have also put in substantial time.

**Comment by aappling-usgs** [comment]
reopening so @lindsaycarr and @jread-usgs can add their hours estimates

**Comment by jread-usgs** [comment]
I've spent 1 hr on the key story ideation and 40 minutes mocking up content for https://github.com/USGS-VIZLAB/water-use-15/issues/115

**Comment by lindsaycarr** [comment]
I've probably spent ~4 hrs

**Comment by aappling-usgs** [comment]
:+1:
