### ISSUE TITLE
Import keystoriesmap from viz-scratch

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#200]
Goal: keep the keystoriesmap sorta reproducible while doing the smallest amount of work necessary to get it there.

Put it in its own subfolder within scripts/ and give it its own remake file, sitting next to preprocess.yaml. 

We're going to accept some non-reproducibility in the sense that the code in this subfolder/remakefile will only get us as far as a map with pies and some black outlines to circle specific regions. The rest - adding text, adding the rest of the outlines - will still be done manually in photoshop.

**Comment by lindsaycarr** [comment]
Lindsay is going to push her local changes into viz-scratch first, then someone else can take over.

**Comment by lindsaycarr** [comment]
Need https://github.com/USGS-VIZLAB/viz-scratch/pull/8 to be merged before you can do anything. Then my initial work is done.
