### ISSUE TITLE
Test & fix drag/drop figure on mobile

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#201]
Follows #186 and a push to beta

**Comment by aappling-usgs** [comment]
Looking on beta right now - on my Android Moto G5S Plus, when I attempt to drag a state I end up selecting text (usually the state bar labels in the rankEm figure) and can't get the state to drag. The map is also very small for selecting a state, which would probably be helped by #234 .

On the bright side, tapping on states or bars in the figure works beautifully.

**Comment by jread-usgs** [comment]
I was able to eventually grab a state, but I otherwise had the same problem, hence #234 
I think we should treat the text the same as other svg text and add css properties to make it so you can't highlight it. Should be an easy fix for that.

**Comment by lindsaycarr** [comment]
Just tested this with most recent changes on beta. So much better! Comfortable with declaring this complete!
