### ISSUE TITLE
Circles added via D3

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#22]
We may want to pre-scale the circle radii in R, if that choice affects performance. Would be nice to know whether it has a noticeable effect or not.

**Comment by lindsaycarr** [comment]
Scaling formula worked out here if we keep in R: https://github.com/USGS-VIZLAB/water-use-15/blob/master/scripts/process/scale_values.R

**Comment by lindsaycarr** [comment]
2 hrs so far

**Comment by aappling-usgs** [comment]
do you agree that this is resolved, @lindsaycarr , given that there's also #38 to address transitions? or do you want to hold out for more experimentation with performance options?

**Comment by lindsaycarr** [comment]
I was going to hold out for when I hooked up css to these for changing the colors with button changes. Or do you think that's a different issue?

**Comment by aappling-usgs** [comment]
Sure, that's fine. I think we're headed for some overlap with #38...are you up for owning (being assigned to) both of them?

**Comment by lindsaycarr** [comment]
yep! let's just close this then, and I'll do that with #38
