### ISSUE TITLE
Optimize circle scaling when loading to state view

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#220]
Captured by Lindsay in https://github.com/USGS-VIZLAB/water-use-15/pull/213#issuecomment-382861813

Copying that issue here:

There are some load time issues because scaling of the circle stroke width has to happen at the same time for as the updateView is called to get counties loaded, which means you have to wait for counties to load. These links directly to the state view will be small, so I don't want to spend too much time right now. We could think about optimizing all of that county loading. Here's the issue in a GIF:

![39015132-0e1f6f26-43e2-11e8-8f63-1a8fc3cd15ba](https://user-images.githubusercontent.com/12039957/39146754-833aba42-46ec-11e8-901d-c07d94614198.gif)

**Comment by jread-usgs** [comment]
No longer relevant?

**Comment by lindsaycarr** [comment]
Yeah, this was fixed for two reasons - 1) we took away strokes (https://github.com/USGS-VIZLAB/water-use-15/pull/289/commits/88448352ff952cd2f4b4eceebf4961a77769296f), and 2) we actually scaled the circles on zoom (https://github.com/USGS-VIZLAB/water-use-15/pull/272/commits/3875957c3732d192adf2ca74c9c974cd1ea3d97d).
