### ISSUE TITLE
Request draft text from NWULT

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#23]
The WU team will write the content-oriented text; we just need to ask them at the right time.

**Comment by lindsaycarr** [comment]
I'm moving this to by April 13 because I want them to be able to see the demo on March 15 and then start writing this. I think we need to have it incorporated by April 13, so we should give the NWULT an earlier deadline. I'm thinking April 2. That's two weeks and feels reasonable.
