### ISSUE TITLE
Mobile version of Rank'em?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#234]
Not sure if this is needed, but a quick preview on mobile makes me think the orientation of our fig and scaling will be hard to see/read in mobile portrait mode.

By having a mobile version of the `scaleX` and `scaleY` and text placement should allow us to shift this fig around and keep all of the other interactions the same. 

Maybe worth it?

![image](https://user-images.githubusercontent.com/2349007/39216819-d11198de-47e2-11e8-9f2b-2299ed2deb52.png)

**Comment by aappling-usgs** [comment]
That does look pretty slick in that arrangement....I'm not opposed, depending on time/people availability.
