### ISSUE TITLE
Adjust map instructions for mobile

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#235]
The current instructions are appropriate for desktop:

> Interact with the figure by clicking or hovering on the map and categories. Click the map to zoom in and look more closely at counties.

Maybe something more like this for mobile:

> Tap the buttons to view a different water use category. Tap or select a state from the drop-down menu to zoom in, then tap on counties or select a county from the second drop-down menu to see county-level water use.

**Comment by lindsaycarr** [comment]
My attempt with the current directions was to let it apply for both desktop and mobile, which I clearly missed. If doing this is more complex than we should do today, let's just edit the current text to say:

> Interact with the figure by selecting or hovering on the map and categories. Select a location on the map to zoom in and look more closely at counties.

People on mobile can figure out that "selecting" means "tapping" and that hover doesn't apply to them.

**Comment by aappling-usgs** [comment]
That's true that people should be able to figure this out...but would dynamic directions really be all that hard?
