### ISSUE TITLE
Medium-res county boundaries for mobile

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#255]
Alternative to implementing #189 is to use something less than the current high res, more than the current low res, for mobile.

**Comment by aappling-usgs** [comment]
Could be low-res across continental US and medium-res for islands

**Comment by lindsaycarr** [comment]
Hmmm I'm not seeing outlines (even crude ones) for two of the VI islands on mobile or desktop.

![image](https://user-images.githubusercontent.com/13220910/39413238-06671244-4bed-11e8-9e17-eb7b94ba8b5f.png)

**Comment by aappling-usgs** [comment]
The low res version used for desktop at national view does not have those islands at all (the circles exist but not the boundaries), but I thought we were OK with that because they become visible once you zoom in. I am seeing the boundaries for those islands on beta right now - maybe you just need to reload after setting developer tools to mobile?

**Comment by jread-usgs** [comment]
I see them on actual mobile (my phone) on beta, but I do not see them on devtool's version of mobile  even w/ a completely fresh session. Is the mobile detection based on some part of the device that chrome's tool isn't triggering?

**Comment by jread-usgs** [comment]
I think we should consider this done

**Comment by lindsaycarr** [comment]
Lindsay's comment above https://github.com/USGS-VIZLAB/water-use-15/issues/255#issuecomment-385299122 is going to be fixed a la #316.
