### ISSUE TITLE
Legend adjustments

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#257]
- [x] Can the "off" category bar widths be only slightly shorter than the active category bar? Instead of much shorter (see Marty’s mock-up)
- [x] ~have category transitions include a bar width shrink/expand w/ the same duration as the dot transition - this is a d3 thing but is as simple as finding the command where the bar lengths get changed and then inserting `.transition.duration(500)` (or whatever the right duration value is) between the selection and the style/attr calls in that command.~ moved to #300 
- [x] in mobile portrait mode, the left (category name) and right (category value) buffers in the rectangle are too large. they should be smaller and the rectangles should be ~20% taller. also move buttons up into the map a little to make them fit (reduce the buffer between map and buttons, and/or reduce the map height + expand the zoom)
![image](https://user-images.githubusercontent.com/12039957/39336460-810f18b2-496c-11e8-9d3e-f94bb6340cb9.png)
- [x] try having the "off" categories show up as colored rect borders instead of grey fill? We are grey-heavy right now, and grey also gives the impression that you can't toggle something on. Try with transparent and grey fill, see what looks good
- [x] increase opacity on the category legend background rectangle

**Comment by ldecicco-USGS** [comment]
I don't have @mwernimont 's mockup....so not 100% sure what the first checkbox is asking.

I've done this so far:
![image](https://user-images.githubusercontent.com/1105215/39371358-15fadc32-4a07-11e8-82eb-0ee2c0a34501.png)

So far so good?

**Comment by mwernimont** [comment]
That's it exactly.  I just didn't like width difference.  Much better!

**Comment by aappling-usgs** [comment]
Ooh, that works visually! The white buttons are still clickable as expected, right?

**Comment by ldecicco-USGS** [comment]
Yup, it's just the "filled-button" that the style is adjusted, the user events all happen on the invisible "mouser-button".

**Comment by ldecicco-USGS** [comment]
I can't believe how hard I'm struggling to get the opacity to update. I think I'm only updating the opacity of the stroke maybe? It looks like this:

![image](https://user-images.githubusercontent.com/1105215/39373537-868cf632-4a0d-11e8-8b82-6ab6b7b51f65.png)

Here's one of the million iterations I've tried:
```
  waterUseViz.elements.buttonBox
    .selectAll(".button rect")
    .filter(".filled-button")
    .style('opacity', 1);
```
When I inspect, it says:
![image](https://user-images.githubusercontent.com/1105215/39373607-b2a14cbe-4a0d-11e8-9d23-818542da3afe.png)

But as you can see from my screen shot, the "fill" isn't opacity of 1, maybe just the stroke part is....
