### ISSUE TITLE
Embeddable figures

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#26]
The national and state views should be embeddable, which I think means
(1) a figure-only html page should be available for each view, and
(2) there should be a button / buttons on the main page that provide the embeddable links

**Comment by lindsaycarr** [comment]
Related to https://github.com/USGS-VIZLAB/vizlab/issues/188 ?

**Comment by lindsaycarr** [comment]
Closed by #54. Took 1 hr.
