### ISSUE TITLE
Revise key stories text in image

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#264]
- [x] “U.S.” and “US” not consistently used in key stories and the rest of the page
- [x] Remove outline and arrow for Irrigation blurb--this statement is true of most of the West, we feel it doesn’t need to highlight the Central Valley of CA
- [x] Key stories placed on top of the map are hiding a lot [of the pies].  Can the aquaculture blurb move above the border? Can the background of the others be made a little more transparent?
- [x] Need to remove the word “what” from the “Irrigation occurs in most areas of the country, but is larger in areas where rainfall is insufficient to meet crop what needs, such as in the drier parts of the West.” 
- [x] In the Public Supply key story, make “domestic” not bold, not capitalized
- [x] New version of the industrial blurb for Lake County, trying to de-emphasize the statement about the specific drivers and Lake County, since we don’t have the information about  whether current steel production in that county still uses local ore, coal, etc: “Industrial withdrawals are driven by many factors. Historically, steel production developed in areas with access to large amounts of water, good transportation, and ore and coal deposits. Lake County, Indiana, on Lake Michigan, accounts for 8% of the US industrial water withdrawals, largely for steel production.”
- [x] New version of the industrial blurb for the Gulf Coast, to get rid of “hotspot”: “Industrial withdrawals for the chemical and petroleum industries occur along the Gulf Coast.”

**Comment by mwernimont** [comment]
My only question is why we care the Agriculture blurb is hiding the circles?  We have the two highlighted, if we wanted to show all those dots as something important, why are we only circling those two?

**Comment by aappling-usgs** [comment]
You're talking about the aquaculture, not agriculture, blurb, right? I think the idea behind that one is that the county-level pie charts are interesting everywhere. We omitted pie charts from the interactive fig for performance reasons - therefore, the pie map figure has two purposes: provide a place for the pie map + provide guidance on interpretation. It can serve both purposes only to the extent that all pies are visible here. 

I see your point that these two purposes for the fig might be at odds, especially when you add in the need for it to look good. Use your best judgment, but I think an attempt to make it look good + have more pies visible would be useful.

**Comment by mwernimont** [comment]
![wu_stories_mobile_left](https://user-images.githubusercontent.com/6390096/39370179-e5fbba9a-4a03-11e8-981f-89e5772de465.jpg)
![wu_stories_mobile_right](https://user-images.githubusercontent.com/6390096/39370180-e60b5a68-4a03-11e8-8fb4-741d015a71ba.jpg)
![wu_stories_static](https://user-images.githubusercontent.com/6390096/39370181-e61fdad8-4a03-11e8-95aa-c791ac3285fc.jpg)
