### ISSUE TITLE
Do something (or not) about blips when circles go to zero.

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#271]
This happens because as the radii got to zero during the transitions and has something to do with the strokes. Since we are using one path for all circles (which does feel A LOT snappier but I didn't want to spend time on actually measuring performance), we cannot figure out which ones will go to zero and make their stroke transparent to prevent that flash. 

So, we have two options 1) keep the strokes and deal with the flash, or 2) remove strokes altogether and not have that weird blip thing happen. I've attached gifs depicting this. To be honest, not having stroke outlines on the circle is not quite as crucial now that we have circles scaling on zoom - there's not quite as much overlap. The other thing to consider is that without strokes, the national map looks very bare because the tiny tiny ones are even less visible.

@jread-usgs and @aappling-usgs what do you think?

**Comment by jread-usgs** [comment]
Agreed. Strokes are not worth it

**Comment by jread-usgs** [comment]
fixed?

**Comment by lindsaycarr** [comment]
Yep, we removed strokes in #289 which was the issue.
