### ISSUE TITLE
use consistent rules for transitions

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#299]
Current version has `applyZoomAndStyle` using a transition duration > 0 if it is desktop with immediate transition if on mobile (for performance reasons). This was also in the category transition for circles but got lost when we moved back to defining them w/ paths (see comment: https://github.com/USGS-VIZLAB/water-use-15/pull/294). We also are using transitions on the legend #276 but need to apply the same rules there. 

Perhaps a single map global for transition duration could be set and used in all of these places?

**Comment by lindsaycarr** [comment]
I don't think I see what was lost from redefining the paths. It still uses that defined `transitionTime` variable. Still kind of on board with consistent transition rules, but also think that this isn't super high priority.

**Comment by jread-usgs** [comment]
You are right, it was the circles as circles part of the code that had the duration hard-coded :+1:
Note that part is still there (commented out) in case we end up using circles for some reason.
