### ISSUE TITLE
Go all in w/ legend transitions or have them switch immediately?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#300]
I really like the update to the legend w/ the transition (https://github.com/USGS-VIZLAB/water-use-15/pull/276), but I don't know if we can go halfway on it. Parts of that legend have transitions (bar width) and others blink immediately (e.g., fill of the bar, text) and it looks awkward to have the value text not move with the right side of the bar as it animates. I think it also needs to have a consistent look after a fresh load and after you switch categories (bar widths differ between these cases). 

I think we are at a juncture where we need to decide to go further or decide to pull back a bit and remove the transition. I am proposing option 2, but w/ us branching the current implementation to be picked up if it is deemed a priority later - mostly because of what I think the complexity/time going "all in" with legend transitions would require.

**Comment by ldecicco-USGS** [comment]
You are the style guru....but as usual...I actually liked that the text and fill switched immediately so you knew there was something changing, and the length of the bar changed at the same rate as the colors on the map. Now that we have it set up, I think we can add transitions to all of that. I haven't paid close enough attention...can we speed up the transitions now that we've made so many efficiency updates? A full second seems really slow.

**Comment by ldecicco-USGS** [comment]
"looks awkward to have the value text not move with the right side of the bar as it animates"....I would also very much disagree with that....text moving is going to look super awkward. The more I read what you are proposing, the more I agree that we should drop transitions and just switch right away.

**Comment by aappling-usgs** [comment]
Notes from https://github.com/USGS-VIZLAB/water-use-15/pull/276#issuecomment-386620256 seem to be the most recent discussion on this issue:
LC: Trying to piece together the conversation here and in #300. Is the final code here fixing that issue or do we still have some more decisions to make around that?
LD: The code here is ready to merge. It includes no transitions (although there is commented out code that shows how to start if we want to go down that route). We can merge this and leave 300 open to work on.

Looks like we have immediate switching for color, shape, and text position on dev now, which appears to be the option most heavily advocated for above. I think the instant changes look fine and agree that it's an advantage to have some part of the interactive graphic changing instantaneously so users know they're being listened to. So...are we good to close this issue, @jread-usgs ? Or do you still want to try the all-in option?

**Comment by jread-usgs** [comment]
I'd prefer to close it and agree w/ what was said above.
