### ISSUE TITLE
Small fixes for national pie map figs

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#305]
This was brought to our attention from IPDS reviewers.

- [x] Remove the word `what` from the irrigation sentence.

"Irrigation occurs in most areas of the country, but is larger in areas where rainfall is insufficient to meet crop ~what~ needs ... "

- [x] ~We might need to adjust the public supply statement, but I can't look into it right now. The comment was: "the public supply note the statement is incorrect for at least New York State (refer to New York counties listed above as well as Delaware and Ulster Counties)."~ Adjust public supply statement to say "are generally highest in counties..."

I believe this was because those values weren't showing up with the path issue (see #https://github.com/USGS-VIZLAB/water-use-15/pull/294) but I'm not sure. Here was the related comment: "At a first glance at the interactive map there appears to be no public supply use in Baltimore City, MD, Washington DC, and several counties in New York (Kings, Queens, Richmond, New York)"

**Comment by wdwatkins** [comment]
Yeah, looks like there is no public supply for those counties on dev or beta.

**Comment by lindsaycarr** [comment]
Hmm I feel like it is fixed on dev. The only one I don't see a dot for is DC, but the value is 0.05

![image](https://user-images.githubusercontent.com/13220910/39580842-559464c2-4ea7-11e8-95bc-6519e32d3822.png)

**Comment by jread-usgs** [comment]
I think it is just too small to see/render:
![image](https://user-images.githubusercontent.com/2349007/39584538-4bf5fdf2-4eb8-11e8-896c-cbb7e9a7a606.png)

see county w/ 10x the WU of DC is barely visible.

**Comment by lindsaycarr** [comment]
@mwernimont the two check boxes correctly state what text needs to be updated in those figs. Should be the last time you need to recreate them :)
