### ISSUE TITLE
Question - should we add "other" to the main fig?

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#308]
Reviewers note:

> You mention the "other" category in the pie chart and in the national map with notes about high water use, but you do not show it in the interactive map.

I don't remember if we have considered this since we have removed the pie charts from the interactive figure. I don't think that seeing "other" in the interactive figure will be of much use since those would be much smaller circles than even public supply right now. However, I am thinking that we might want to include a note in the legend or the figure caption below that states that these are only showing the four major categories. I realize this is stated below, but might be important to say it in this figure in case people don't keep scrolling and/or if people take a screen shot of that first figure. My vote would be for a bit of text right below the legend.

Perhaps something like:

![image](https://user-images.githubusercontent.com/13220910/39608746-f7288b34-4f00-11e8-97ca-b7567809d8e1.png)

**Comment by jread-usgs** [comment]
I'm not sure we can include that text, since to the user, total is one of these categories, and makes up 100%. 

I'd prefer to push back on this reviewer comment, since "other" is covered in text, in the national pie, and in the national pie map. I also don't think we should add "other" as a category to the interactive (agreed).

**Comment by lindsaycarr** [comment]
Currently this is what is happening

> I'm not sure we can include that text, since to the user, total is one of these categories, and makes up 100%.

but I think this is exactly what we want to avoid. Not that people would, but if someone added these categories up for a state or county, they would not get the same number as the total. So, I think we should include this somewhere. I'm trying to think of the best way to word it...

> Four additional categories are too small to include on their own, but are represented in total. See more about "other" categories below.

**Comment by lindsaycarr** [comment]
@jread-usgs did you have any thoughts on my comment above? I'm trying to think like a user and feel like it would be misleading to not give some sort of note that says we aren't showing the tiny tiny categories.

**Comment by jread-usgs** [comment]
I would prefer to leave it out of figure one. Anyone who cares enough to add up the numbers for a state will (hopefully) scroll down a few ticks and see the pie and get the remainder of the context.

**Comment by lindsaycarr** [comment]
Yeah, I can see both arguments and I'm struggling between keeping things simplistic for the audience and keeping things correct. 

I think I can be comfortable with not even showing a message about the "other" category since people who only see the main figure will still leave with correct information about the big picture distribution of water use (thermo vs irrigation, spatial distribution around cities or the Mississippi River, etc). People could then learn even more by scrolling and seeing the additional context.
