### ISSUE TITLE
Generate state social media gifs

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#31]
Options for this issue:
1. Keep it simple and generate gifs as we always have, or
2. Try to automatically generate custom gifs for each WSC, e.g., for use with their twitter accounts. This may involve a shell/python script to use headless browser to render a d3 in canvas (turn into raster) then capture output as png/gif.

**Comment by aappling-usgs** [comment]
Notes on option 2: last summer's interns took this approach: Node script (written in javascript). uses a node package to create a png from an svg. Mary says, "There is a package that can generate an gif from an svg but I don't know how similar it is to the other one."

**Comment by jread-usgs** [comment]
I think the relevant work is here: https://github.com/USGS-VIZLAB/active-flood-viz/blob/master/floodviz/thumbnail/thumbnail.js

**Comment by jread-usgs** [comment]
would Option 3: `generate gifs w/ R` be different than option 1? (is option 1 a screen capture?)

**Comment by jread-usgs** [comment]
Seems we can use gifsicle to have different delays per frame, which is nice because it lets us have a longer running gif w/o increasing the file size (e.g., frames during transitions are short, frames looking at a category are longer) 
```
gifsicle -b a.gif -d50 "#0" "#1" -d100 "#2" "#3"
```
which [sets the delays of frames 0 and 1 to 50, and frames 2 and 3 to 100](https://www.lcdf.org/gifsicle/man.html)

**Comment by jread-usgs** [comment]
I am working on coding this up for each state+PR. 
 - using a state specific UTM zone to get each state to look good. I am using the median UTM number from [this spreadsheet](http://stateplane.ret3.net/COUNTYSPC.XLS)
 - I think the bounding boxes of states will let us get away with ~3 different kinds of gif layouts: 1) tall (California), 2) flat (North Carolina), or squarish (Colorado). We should be able to do some aspect ratio calc with the bounding box of the sp object.
 - I am adding a USGS watermark and a url to the main viz. 
Here is a starting point for North Carolina w/o pies or legend etc:
![nc_water_use](https://user-images.githubusercontent.com/2349007/37850338-c10cc68c-2ea8-11e8-9551-96237bd9a4f5.png)

**Comment by jread-usgs** [comment]
Not sure if there is a single tool way to do this (this example is [imagemagick](https://www.imagemagick.org) and [gifsicle](https://www.lcdf.org/gifsicle/)):
use R to generate ordered pngs, then imagemagick to turn them into a gif:
```
convert -loop 0 -delay 10 01_CA_water_use_pie0.png 01_CA_water_use_pie1.png 01_CA_water_use_pie2.png 01_CA_water_use_pie3.png 01_CA_water_use_pie4.png 01_CA_water_use_pie5.png 02_CA_water_use_irrigation0.png 01_CA_water_use_pie5.png 01_CA_water_use_pie4.png 01_CA_water_use_pie3.png 01_CA_water_use_pie2.png 01_CA_water_use_pie1.png out.gif
```
then gifsicle to change the frame delays for individual frames:
```
gifsicle -b out.gif -d150 "#0" -d10 "#2" "#3" "#4" "#5" "#6" "#7" "#8" "#9" "#10" "#11"
```
delay of 150 for "pause" frames and 10 for "transition" frames

**Comment by jread-usgs** [comment]
I have the three different types implemented on https://github.com/jread-usgs/viz-scratch/tree/wu_gif_transitions, which are tall (e.g., CA, IN), wide (e.g., NC, TN), squarish (e.g., CO, NE). Things seem to be in good shape for social media release. A few changes I would like to make before bringing the code in: 1) re-order the categories to go from largest to smallest for each state, 2) transition between the pie and three largest categories, and 3) mess around w/ pause durations and frame numbers to get the right feel.

**Comment by lindsaycarr** [comment]
Any reason this is over in scratch and not in this repo? Like how we ported the code for the national map over here?

**Comment by jread-usgs** [comment]
no, no reason. I can move it over as part of progressing through the other GIF tasks.

**Comment by jread-usgs** [comment]
This code is now in this repo
