### ISSUE TITLE
Explore pie charts for total category

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#32]
Could be cool! We'd like to try it, but if they don't look good or don't perform well, we won't use these pie charts in the final product.

**Comment by aappling-usgs** [comment]
1st step: static prototype to see how it looks

**Comment by aappling-usgs** [comment]
2nd step: react to prototype (see #45)

Jordan says: This ended up looking like what I hoped it would - where you get a national view of all of the categories at once, and you can see them stratify spatially. I think it is kind of cool, but I also think it has the potential to overcomplicate what could be a really simple/sharp viz.

Alison says: What about including this view as "Everything" but also having a "Total" view that's just blue circles? I think this one is aesthetically pleasing, which is the first requirement for a successful vizzy. Maybe we should ask some outsiders to give a reaction too, but my first guess is that with both Everything and Total views, the overall viz will be sufficiently simple/clear.

Any other general reactions, ideas for tweaks, opinions on whether to go forward?

**Comment by aappling-usgs** [comment]
Jordan has spent 2 hrs so far

**Comment by jread-usgs** [comment]
Agreed with "everything" and "total". 

An option here too is if the transition between pie to category circle is too heavy for browsers, we could depart from it for the viz and animate the transition for the twitter/reddit gif instead. Noting the risk of implementing this in the viz - if it fails, we still may have a use for it in gif-space.

**Comment by aappling-usgs** [comment]
* Nancy and Cheryl really liked it. We mostly love it too, but probably just because we're nerds
* can be misinterpreted as additional dots on the map - would need extra, careful explanation
* likely to bomb on mobile
* maybe more effective to use as a key story? maybe simplify to thermo vs ag with slider? 
* do we need a focus group to tell us about this?
* remember that this info is largely redundant with what we're already presenting
* we'd need to deal with the gray slices (Other category)
* offer this (static version) as a cool graphic to be used by the WU team as they want - e.g., for them to use in a news release
* write up as a blog? could happen after the viz

gut group response - we're leaning toward not using this in the interactive vizzy...but don't burn the code!!

**Comment by jread-usgs** [comment]
I think it is worth mocking up a gif animation to show what the pie -> category transition would look like. At a minimum, we could provide it to the WU team for future ppt presentations. Also could be part of the social campaign. 

I agree that there is a small downside and risk to including it in the viz - both because of challenges with user interpretation and the practical challenge of writing a performant transition between pie and category.

**Comment by jread-usgs** [comment]
See mockup in slack channel for an example of this w/ transitions between categories. That example is kind of the "windshield wiper" of moving a pie slice to occupy the entire circle. 

A simpler transition between "everything" to a category (e.g., irrigation) could include keeping all of the category pie slices, but scaling the group of slices that define the pie to the area of the category, while at the same time transitioning all of the slice fills to the category color - giving the appearance of a complete single color circle but not altering the pie chart geometry

arc/ or pie-slice geometry in SVG looks like this: 
```xml
<path d="M 1 0 A 1 1 0 0 1 0.81 0.58 L 0 0" fill="purple" /path>
```
(see [Arc section](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) for explanation) 
![image](https://user-images.githubusercontent.com/2349007/36938359-f0d1084c-1ee5-11e8-90e5-aa34d60fb9fa.png)
and assuming one path for each non-zero category per county, we'd have a lot more `path` elements than `circle` elements in the non-pie implementation. Not sure if that is a performance concern or not - I suspect it isn't on desktop and maybe is on mobile.

**Comment by jread-usgs** [comment]
Here is CONUS total vs pies (same style and size, lines, etc) for comparison

![circle_map_clean_total](https://user-images.githubusercontent.com/2349007/36951290-952d4ac2-1fc7-11e8-92de-123d0b0a3b5e.png)
changed public supply to ![#2E86ABCC](https://placehold.it/15/2E86ABCC/000000?text=+) and industrial to ![#BA3228CC](https://placehold.it/15/BA3228CC/000000?text=+) and added grey for other. Based on the current number of categories and minimum size, there are 10,741 pie slices for CONUS:
![circle_map_total_clean_pies](https://user-images.githubusercontent.com/2349007/36951291-953ea0e2-1fc7-11e8-8584-c11dcdbaa969.png)

**Comment by aappling-usgs** [comment]
Calling this done with respect to exploration. We're going to try it, leaving ourselves an out if the technical challenges turn out to be too big.

**Comment by jread-usgs** [comment]
for completeness, the code I used to create the animated gif is on this branch https://github.com/jread-usgs/water-use-15/tree/pie_gif and https://ezgif.com/maker to assemble the gif from the png frames (with 10 ms duration for transition frames and 100 ms for the paused frames)
