### ISSUE TITLE
strange click behavior on apple phones

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#321]
1) on mobile national view tap a non-total category, 2) tap a state and expect to zoom into it, 3) instead see that the category has switched back to total. 

This happens on @jread-usgs phone (iPhone), but not on @lindsaycarr phone (Samsung). Must have something to do with how iOS handles clicks/mouseover/mouseouts?

**Comment by lindsaycarr** [comment]
Well, this is a great description of the issue: https://www.nczonline.net/blog/2012/07/05/ios-has-a-hover-problem/. We were just leaving the mouseover features on mobile thinking that it wouldn't matter, but it does for iOS. I think the solution to this will be fairly easy because we will just make sure that mouseover events don't appear on mobile. That would fix any potential issue with the state-zoom county tapping that @jread-usgs mentioned.

**Comment by lindsaycarr** [comment]
@jread-usgs the state drag-and-drop fig has no click, only mouseover and mouseout. I'm curious what behaviors you experience on your phone that are different from desktop on this one. I don't want to go touching all of that if it is working as expected.

**Comment by jread-usgs** [comment]
Hmm... the state drag/drop seems fine on my phone. `d3.drag()` handles the state moving and that works fine.

**Comment by lindsaycarr** [comment]
OK, I won't touch that part of the code then!
