### ISSUE TITLE
use d3 modules rather than whole d3

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#335]
d3 is by far the largest file - can we use just some components?

**Comment by aappling-usgs** [comment]
first step: determine which modules we need.
1) can we test to make sure that those are exactly and completely the list of needed modules?
2) can we test to see whether it actually saves us time, and by how much? (probably only makes things faster if we can also be using webpack, #334)

**Comment by jread-usgs** [comment]
Not digging into this yet, but the resource I found when I started looking earlier in the week was this: https://stackoverflow.com/questions/44379393/how-can-i-specify-the-d3-v4-micro-library-on-cdn

**Comment by jread-usgs** [comment]
I took a quick stab at stitching the microlibraries we are using into a single .js. It seems to work until we hit `queue`, which seems different than the other modules and also seems to be something that has gone away in v5 of d3 (maybe why its microlibrary is different). From my initial look it seems that we can cut the .js file size down by ~50%, which seems like it _might_ be worth the extra effort, but I am not sure. We could cut that down even more by only exporting the functions from each microlibrary we are using but that is more work too. 
The approach that seems to be the path forward looks like this: https://towardsdatascience.com/d3-js-the-custom-modular-bundle-now-bebd6f25bc8b and https://bl.ocks.org/mbostock/bb09af4c39c79cffcde4

**Comment by aappling-usgs** [comment]
Do you have a list of the microlibraries that you found necessary (recognizing that `queue` isn't quite captured yet)?

**Comment by jread-usgs** [comment]
This is likely incomplete, but:
d3-array, d3-color, d3-collection, d3-scale, d3-geo, d3-selection, and then [d3-queue](https://d3js.org/d3-queue.v1.js) is the one I had trouble with (that is the link to the non-minified). The other microlibraries export things (e.g., [d3-selection](https://d3js.org/d3-selection.v1.js) ), but queue doesn't and I end up with something like `build_map.js?_c=4391381:94 Uncaught TypeError: d3.queue is not a function`

**Comment by jread-usgs** [comment]
I had a conversation with Mary about this, and they are using broserify and it sounds like webpack is likely a better solution for us, but actually much more complicated and has a greater learning curve.

**Comment by mbucknell** [comment]
It's browserify

**Comment by jread-usgs** [comment]
hahah. bro. whoops

**Comment by jread-usgs** [comment]
and seems the issue w/ queue might be related to big changes from v4->v5 of d3, where promises are the new norm.

**Comment by lindsaycarr** [comment]
OK, throwing in the towel on this one. Worked on it again, and I can get promises working in Chrome and everything. It just feels like everything is slower to load with the promises worked in there. I cannot get it to work well in IE - takes forever before you see the dots, and then zooming in throws errors.

You can take a look at changes on `[this branch](https://github.com/lindsaycarr/water-use-15/pull/2)`.
