### ISSUE TITLE
bundle and minify css files

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#336]
is this the same solution as #334? if so, resolve both at once; otherwise, prioritize just getting something working for #334 and see if we can learn any more about the potential in future efforts

**Comment by aappling-usgs** [comment]
Notes (no idea how relevant/useful these are yet):
* https://stackoverflow.com/questions/42086079/webpack-1-12-bundle-css-files?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa suggests that there are webpack plugins for css
* https://github.com/webpack-contrib/mini-css-extract-plugin is one such plugin

**Comment by aappling-usgs** [comment]
assigning to marty not because this HAS to get done by release but because if it does, marty will be the one to do it.

**Comment by lindsaycarr** [comment]
Fixed by #365
