### ISSUE TITLE
For GIFs, make sure a "0" use is not drawn as a dot

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#349]
I haven't verified this, but I think some counties that are 0 for a category still get a tiny dot because there is a small stroked on the outer edge of the dot/pie.

**Comment by lindsaycarr** [comment]
@jread-usgs is this still relevant?

**Comment by jread-usgs** [comment]
No, I haven't checked this to verify there is *no* dot plotted when the category is zero.

**Comment by jread-usgs** [comment]
The lesser res gifs look better after taking away the stroke on the pie, which is what was causing this. fixed now.
