### ISSUE TITLE
larger dot size

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#359]
Cheryl is wondering if we can increase the dot size slightly since you can't really see any dots for public supply and industrial.

Beta right now:
![image](https://user-images.githubusercontent.com/13220910/40804358-9f6ff8e6-64e0-11e8-822c-0480da0c6480.png)

![image](https://user-images.githubusercontent.com/13220910/40804366-a6d41356-64e0-11e8-95cd-e2be55f09cb4.png)

**Comment by lindsaycarr** [comment]
Maybe make the whole map bigger and eliminate some white space, too

**Comment by lindsaycarr** [comment]
Total right now:

![image](https://user-images.githubusercontent.com/13220910/41440873-d95b9d42-6ff5-11e8-88e4-386d73ee9aa8.png)

**Comment by lindsaycarr** [comment]
Adjusting https://github.com/USGS-VIZLAB/water-use-15/blob/master/js/build_map.js#L53 to accomplish this, but it is really just making the larger categories look way more crowded and not boosting the smaller categories much. 

With 15 instead of 10:
![image](https://user-images.githubusercontent.com/13220910/41469841-669e2f84-7074-11e8-948a-148cdcfedc51.png)

![image](https://user-images.githubusercontent.com/13220910/41469860-745d5398-7074-11e8-8446-9258a5586435.png)

**Comment by jread-usgs** [comment]
I prefer 15.

**Comment by lindsaycarr** [comment]
Huh wow, ok. I thought that it might be too crowded. I guess not? Here's the difference:

![size15_publicsupply](https://user-images.githubusercontent.com/13220910/41470615-babfa0e6-7076-11e8-895e-d92dc50ded66.gif)
![size15_total](https://user-images.githubusercontent.com/13220910/41470619-be243300-7076-11e8-8607-4368a01ee918.gif)
