### ISSUE TITLE
combine all js files into one

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#366]
No reason not to combine the d3 js file(s), and files that go into `all.min.js` into one big master minified js file.

**Comment by aappling-usgs** [comment]
Cool! Why not? I thought we needed to inject build_map.js within the html body (after the DOM is declared)?

**Comment by lindsaycarr** [comment]
Oops, you're right on that one. Wasn't thinking when I wrote that. Well, we can do d3 modules + our other custom js! I corrected my initial comment.

**Comment by lindsaycarr** [comment]
We are looking into using webpack, which might make this custom function irrelevant. First attempt in a new repo: https://github.com/USGS-VIZLAB/gage-conditions/pull/6
