### ISSUE TITLE
Update vizlab landing page

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use-15#37]

**Comment by lindsaycarr** [comment]
Get better description in viz.yaml

**Comment by lindsaycarr** [comment]
Up and running thanks to @ldecicco-USGS locally building:

**ldecicco**
> FYI....I don't think the landing page works via Jenkins yet (unless you fixed it...I did not)
> I've been building it locally and pushing it up by hand
