### ISSUE TITLE
Transitions for switching categories

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#38]
Write the functions that are triggered by the buttons in #21

**Comment by aappling-usgs** [comment]
This issue now includes hooking up the buttons so that they trigger category changes, as well as making those category changes look nice or at least acceptable.

**Comment by aappling-usgs** [comment]
If it's easy, want to spend a few minutes experimenting with also hooking up the buttons so that hovering over a button temporarily displays the hovered-over category (and then reverts when the mouse moves off)? If it's hard, feel free to kick that idea over to #63 . But I think it's just a matter of (1) adding the same function to on('mouseover') that you'll already be adding to on('click'), plus some state tracking so that on('mouseout') can switch back to the most recently clicked category.

**Comment by jread-usgs** [comment]
Seems this is complete?

**Comment by aappling-usgs** [comment]
Good with me. Lindsay said in PR that this took 2 hours.
