### ISSUE TITLE
Create social links

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use-15#52]
https://github.com/USGS-VIZLAB/water-use-15/blob/master/viz.yaml#L85

**Comment by lindsaycarr** [comment]
Icons added in https://github.com/USGS-VIZLAB/water-use-15/pull/49, took @ldecicco-USGS 1 hour. The rest of this task needs to add the actual language used for when someone clicks "tweet this" and gets a prompt for a tweet.

**Comment by aappling-usgs** [comment]
@ldecicco-USGS and @lindsaycarr , what do you think about this in context of the NSF VIZZIES competition? Should we hide the social media icons for a few weeks? Or just leave them dormant? Or attach a dummy URL that communicates to the judges that we intend to make this active once we release the vizzy?

**Comment by ldecicco-USGS** [comment]
This should have been closed with #165

**Comment by lindsaycarr** [comment]
Nope, this is open to capture the need to have the text populate when you click the button (see my Mar 1 comment above).

**Comment by aappling-usgs** [comment]
these are in the social media release plan spreadsheet

**Comment by aappling-usgs** [comment]
these URLs (with suggested text) will need to get copied from the spreadsheet into the viz.yaml in the `social-links` block within the `parameter` section, which currently looks like this:
```
  - 
    id: social-links
    github: https://github.com/USGS-VIZLAB/water-use-15
    twitter: https://twitter.com/share?url=https://owi.usgs.gov/vizlab/water-use-15/?utm_source=twitter_button_share
    facebookLink: http://www.facebook.com/sharer.php?u=https://owi.usgs.gov/vizlab/water-use-15/?utm_source=fb_button_share
```
