### ISSUE TITLE
Create thumbnails

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use-15#53]

**Comment by lindsaycarr** [comment]
See ImageMagik script used in Hurricane Irma - https://github.com/USGS-VIZLAB/hurricane-irma/issues/110#issuecomment-329227314

**Comment by aappling-usgs** [comment]
We need a first thumbnail or GIF in time for the vizzy submission (~April 13)

**Comment by aappling-usgs** [comment]
Starter code for an R-based GIF is at https://github.com/USGS-VIZLAB/viz-scratch/tree/master/water_use_gifs, looks something like this:

![water_use_2015_animation_pub_irr_pies](https://user-images.githubusercontent.com/12039957/38432475-655bf694-397c-11e8-9013-c8301a51cfb8.gif)

**Comment by lindsaycarr** [comment]
@ldecicco-USGS you are assigned this, but that was a month ago. Still interested or should we reassign to someone else? Also, the code to generate a static national pie map now lives in this repo (see https://github.com/USGS-VIZLAB/water-use-15/blob/master/piemap.yaml), and I think we can reuse it to make various thumbnail sizes.

**Comment by ldecicco-USGS** [comment]
How about we open up the issue to someone for now. I'm going to spend the morning to see if I can get the original vizzy up-to-date.

**Comment by lindsaycarr** [comment]
Tool to check if they are working properly: https://help.medium.com/hc/en-us/articles/215769058-Update-Facebook-Twitter-cards

**Comment by lindsaycarr** [comment]
Facebook looks good, but has two warnings:

![image](https://user-images.githubusercontent.com/13220910/40305772-0035c788-5cca-11e8-8eb5-49ae5ca0b96e.png)

```
Invalid OG URL: The given value '' for property 'og:url' was not a valid absolute URL.
```

Twitter is being cut off slightly at the bottom, so I need to adjust the size:
![image](https://user-images.githubusercontent.com/13220910/40305837-3db0ddf0-5cca-11e8-8869-7c208e0918a0.png)

**Comment by lindsaycarr** [comment]
Twitter actually needs a 2:1 image (see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image).

**Comment by lindsaycarr** [comment]
Ugh, following the directions for image size, but still cutting if off..... 👊 

![image](https://user-images.githubusercontent.com/13220910/40323665-1aed256e-5d04-11e8-8404-d5f4fcc7128c.png)

**Comment by lindsaycarr** [comment]
^ I can't figure out why that would be getting cutoff. Everything I read says to use a 2:1 aspect ratio which that is...
