### ISSUE TITLE
"Get the code" link in footer seems wrong

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/water-use-15#60]
Currently going back to main link (not github)

**Comment by lindsaycarr** [comment]
This should be a vizlab issue, not a water use viz issue. I noted this awhile back for how-to-gdp https://github.com/USGS-VIZLAB/how-to-gdp/issues/52. I made this vizlab issue https://github.com/USGS-VIZLAB/vizlab/issues/339

**Comment by lindsaycarr** [comment]
If this gets fixed by fixing for all of vizlab through https://github.com/USGS-VIZLAB/vizlab/issues/339, hours won't count towards water-use-viz. A fix exclusively in water-use would. Opening to be able to make sure it happens.

**Comment by lindsaycarr** [comment]
@ldecicco-USGS how long did this take? We will count hours for this guy as just "vizlab".

**Comment by ldecicco-USGS** [comment]
OK, <1 hour
