### ISSUE TITLE
embed title is category "undefined"

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#67]
![image](https://user-images.githubusercontent.com/2349007/36938824-00f56c8e-1eed-11e8-88ae-68266b4e11cb.png)
refreshing it gets you `total`, but entering the embedded fig is `undefined`

low priority for now, but don't want to forget to test later

**Comment by ldecicco-USGS** [comment]
Another thing that may or may not be related, but if we change any required content for the `wateruse_page` specifically for the map....we need to double-check that also gets put into the embed `national-water-use` page. 

We need some sort of "testthat" for non-packages that could be kicked off on a travis run....

**Comment by aappling-usgs** [comment]
It's not just embedding but also the main page, e.g., http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/vizlab/water-use-15/#view=USA&category=irrigation. Maybe it's as simple as passing in `activeCategory` to the first call to `updateCategory` on this line https://github.com/USGS-VIZLAB/water-use-15/blob/master/js/build_map.js#L71 ?

**Comment by aappling-usgs** [comment]
we should also be converting to the nice category name...or maybe just removing the dynamic part of the title...
