### ISSUE TITLE
Implement pie charts with basic transition

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#71]
Try with D3. Remember that we have the option of doing this on the R side instead if needed.

**Comment by lindsaycarr** [comment]
Effort up until PR #83 for Lindsay: 3 hrs.

**Comment by aappling-usgs** [comment]
This is done. I'll lump all my task hours into a single issue later, probably #97. @lindsaycarr , you'll do the same, right? in #97 or in another appropriate issue?

**Comment by lindsaycarr** [comment]
Well, I think the hours I wrote above are good to leave here. I will make sure to write hours I spent on #102 into issue #97.
