### ISSUE TITLE
Spruce up pie chart transitions

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#72]
Follows on #71

**Comment by lindsaycarr** [comment]
Might be interesting to make all of views pie charts but filter data so that it's only one category. Then I think the fancy windshield wiper transitions would work.

https://bl.ocks.org/rshaker/225c6df494811f46f6ea53eba63da817

**Comment by jread-usgs** [comment]
We've discussed a few transition options that might help w/ performance. 

The _windshield wiper_ looks good, but if it isn't smooth and dogs the browser it won't look so good
The _color transition_ seems to be a simpler option, but maybe the color interpolation is going to be challenging to make smooth
Another idea is the _coin flip_ transition, which takes advantage of being able to avoid the color interpolation **and** letting us stagger the transitions left to right (if that helps us) while making it look purposeful. 

for the _coin flip_ transition, say we are doubling the size:
If the transition total time is 1 second, the first 0.5s scales x from 1 to 0 while scaling y from 1 to 1.5. At time 0.5s, you are looking at the "edge of the coin" (only the stroke width) and we instantly flip the fill color(s) and add/remove pie paths (if relevant). Then from 0.5 to 1s we scale x from 0 to 2 and y from 1.5 to 2.

It seems the color transition may be one of the more expensive things happening in our various options for transitions [source](https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/) but note that reference is pretty dated.

**Comment by aappling-usgs** [comment]
We're trying lots of things, but at this point I'm finding it hard to separate this issue conceptually from #97, so i'm going to close this one in favor of just adding comments to that issue.
