### ISSUE TITLE
clean up prototypes

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#74]
maybe we leave them in for now, but `centroid_sizes`, `circle_map_total`, `circle_map_thermoelectric`, `circle_map_publicsupply`, `circle_map_irrigation`, and `circle_map_industrial` are all viz items that don't make it into the dynamic viz and use different methods for preparing both spatial and water use data.

ultimately i'd like to see us either streamline the methods (if we find another use for these prototypes) or delete them.

**Comment by jread-usgs** [comment]
Yes, I think they should be removed and I always feel a bit odd about where the prototyping stuff fits into the viz repo. Should it be separate and included in `viz-scratch` in the future? Is that too decoupled or redundant from the data fetching/processing steps?

**Comment by aappling-usgs** [comment]
Not sure - seemed like the right place at the time, but maybe the cleanup effort would have been smaller if we'd kept it separate in `viz-scratch`.

**Comment by aappling-usgs** [comment]
Since you're good with removing, and I'm hitting errors in trying to get them to work again with some recent spatial data changes. I'm going to remove them right now.

**Comment by aappling-usgs** [comment]
closed by #75
