### ISSUE TITLE
Pie chart performance

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#82]
Nodes keep appending, rather than update (for pies).

![image](https://user-images.githubusercontent.com/13220910/37539483-d33e8926-2921-11e8-8d57-228525dc7d50.png)

After hovering over pie chart and then back:

![image](https://user-images.githubusercontent.com/13220910/37539588-134db58c-2922-11e8-8e6c-7689606caf6c.png)

**Comment by jread-usgs** [comment]
redundant with #97 ?

**Comment by lindsaycarr** [comment]
Well yes, now that #97 exists it appears to be redundant :) Although the particular issue mentioned above about appending new nodes rather than updating was fixed between Alison and I yesterday and will come through the next time I merge my branch. See https://github.com/lindsaycarr/water-use-15/tree/piechart-performance

**Comment by aappling-usgs** [comment]
Oh, rats, sorry, I looked for existing issues but somehow didn't spot this one.
