### ISSUE TITLE
Prototype button options (S)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#89]
Create a mock-up for category & water use volume legend layout for:
- national view in desktop
- national view in mobile
- state view in desktop
- state view in mobile

Initial discussion of options at https://docs.google.com/document/d/17Q0Ei2hxmlmFHgmSWZ2hxtzhKxnJJGKWfE5BqNl4LOY

**Comment by aappling-usgs** [comment]
I like the overlay on desktop zoom. Add a touch more buffer (larger overlay rectangle)?

Also add a bit of vertical buffer between mobile map and mobile buttons?

I'm not sure I love the one longer bar. It's OK, but...what about making the grey bars shorter, so Thermoelectric has the same grey space on either side of the word? Or making them all long enough to always accommodate a number without growing? Or what about centering everything in mobile - text within bars, title, and bars (where one could be longer than the others but symmetrically left and right)?

Could we do smaller buttons in mobile? And adjust them a bit to the left, or else center them if we use all same-size bars?

Maybe drop 2015 from the button title, just keep it in the vizzy title.

Move the `(millions of gallons per day)` to be a subtitle to the legend title? I think people would notice & use that info more quickly if it were a subtitle.

Interesting idea to put the watermark by the footnote in mobile. Would moving the footnote to the subtitle mess that up aesthetically? I think it could also reasonably still live on the map, but I prefer what you've proposed (below the buttons).

What technology did you use to prototype these?

**Comment by jread-usgs** [comment]
@aappling-usgs I used powerpoint to mock these up and would be happy to share the file if you would prefer that.

As for the bar lengths and details related to it, I was thinking we could wait on seeing how this would look w/ data, which will help determine necessary bar length. 

I was also thinking this category legend could take the place of the tooltips. When you mouse on the county the value and category title would change to update the information to the county being moused over.

**Comment by aappling-usgs** [comment]
I like the legend = tooltip idea! Trick will be to make it likely that the user will be viewing both the map and the legend when they start playing around, which already seems very likely with the arrangements you've proposed (assuming we include the buttons in the auto-scaling in desktop mode). We might also need to make the change a bit flashy to help users notice (make the button color flare or size expand for 0.5 seconds or something), but I think it's safe to start with the expectation that changing the text will be enough to draw attention.

**Comment by mwernimont** [comment]
I like the look of it on desktop and mobile.  My question is do the bars need to be staggered?  I think the definitive coloring and numbers attached to the selected category stands out on it own.  I just find even length creates better layout options and less distracting whitespace.  It would center up nicely on mobile so the user could have even more real estate to click categories as well. Maybe even just compromise on no stagger on mobile and stagger on desktop as I don't have as much of a problem on that view.  This is my OCD showing, so we can ignore if we like

**Comment by jread-usgs** [comment]
Agreed Marty - I had mixed feelings about doing that. in the end I think it made the GIF look better: 
![ca_water_use](https://user-images.githubusercontent.com/2349007/38370037-bca31cbc-38ae-11e8-9269-e94e7db823e9.gif)
but I don't feel strongly about doing it and agree that we should consider skipping it for now

**Comment by mwernimont** [comment]
Ah, but in your gif the stagger much more subtle and yet effective, if it was only that I would be cool with it.  The amount of stagger you have in the mockup bothers me.  Would you be okay with a subtle stagger instead like the gif?

**Comment by jread-usgs** [comment]
totally - but the question is - is it better than keeping all bars the same length? I think so for the gif but it is hard to justify it in a static view.

**Comment by mwernimont** [comment]
I guess that's up to us.  If we feel the stagger has no real benefit to the user in the static version then we shouldn't have it.  I feel the small stagger has a benefit visually and doesn't distract due to the small nature of it.  Just emphasizes just that much more which category the User has selected. As long as it's subtle I'm on board with it.

**Comment by aappling-usgs** [comment]
:beers: to @jread-usgs and @mwernimont for good ideas and discussion. @jread-usgs , could you put your design lead hat on to:
* weigh the feedback from @mwernimont and me
* come up with an implementation-ready plan (final enough to implement and specific enough so someone knows when they've succeeded - probably a set of revised images would do it, or doubling down on your current images, or images plus some text describing modifications)
* put that plan in a new GitHub issue
* put your hours estimate in this issue
* close this issue

**Comment by jread-usgs** [comment]
@aappling-usgs we discussed and Marty is creating a new mock-up that we'll bounce off of you before getting into implementation details.

**Comment by mwernimont** [comment]
![water-use-mockup](https://user-images.githubusercontent.com/6390096/38380996-0d5dacfa-38cb-11e8-90ab-e05ec91098d0.jpg)
![mnmockup](https://user-images.githubusercontent.com/6390096/38381003-121f0194-38cb-11e8-9749-83d5a460c626.jpg)
