### ISSUE TITLE
Fix projection weirdness with centroids

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/water-use-15#9]
See #8

**Comment by lindsaycarr** [comment]
@mwernimont how long has this taken you so far?

**Comment by mwernimont** [comment]
Shoot, I would say 4hrs? I'll do better with other task on timekeeping.

**Comment by aappling-usgs** [comment]
Remaining: just need to get Alaska working and check against state polygons when those are available.

**Comment by mwernimont** [comment]
Alaska STATEFIP: 02 COUNTYFIP: 016 has coordinates landing it in Canada which causes the projection cut off the dot which throws an error in D3 and stops all dots from being projected.  A quick fix at the moment is filtering out that COUNTYFIP and correcting it when we have time.  PR here https://github.com/USGS-VIZLAB/water-use-15/pull/69

**Comment by aappling-usgs** [comment]
resolved by #75
