### ISSUE TITLE
Show state borders in national view (S)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#90]
Involves design decision about coloring - should current background get to be lighter or even transparent, in favor of just showing borders? Should the borders themselves be white, leaving the grey states background?

**Comment by jread-usgs** [comment]
For now, let’s add a white stroke to the currently grey polygons. It would be good to lump these style properties (fill and stroke colors) in the same spot in css or be able to easily find in js so we can try various map styles.

**Comment by aappling-usgs** [comment]
Sounds good. As noted on a recent call, maybe someday we can figure out a better place for these (for starters, could move them to their own .js file if that would help)...but in the meantime, i hope editing these properties is relatively straightforward for anyone with this link: https://github.com/USGS-VIZLAB/water-use-15/blob/8c3c20f604388f8c68bd0e917919334e6b7e6871/js/map_utils.js#L6-L32

**Comment by ldecicco-USGS** [comment]
So is this task still to make the background grey and the state boarders white? Or, are we sticking with white background, black boarders, and a grey fill for the hovered county?

**Comment by aappling-usgs** [comment]
@jread-usgs - as design lead, do you approve of the border and state colors or want to change them?

![image](https://user-images.githubusercontent.com/12039957/38334871-72d467a0-3811-11e8-9602-99f9337d4967.png)

**Comment by jread-usgs** [comment]
I think they are in good shape for now, but I wouldn't say they are ready for our release. I do think it is great that we have all of the style parameters in places where they are easy to edit and iterate. Good to call this done, but I wouldn't limit us from refining further.
