### ISSUE TITLE
National view: give circles same hover & click behavior as their backing state (S)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#92]
* Mousing over any circle should emphasize the backing state in the same way as mousing over the state under the circles (for circles that extend beyond their state boundary, does "backing state" mean the one directly behind the mouse or the one represented by the circle?) (S)
* Clicking either a dot or state poly zooms you to the state view (S)

**Comment by jread-usgs** [comment]
For circles extending beyond the edge of a state, “backing state” means the state the dot/county belongs to.

**Comment by aappling-usgs** [comment]
As of #106 + #109, i think really what we should do is remove mouse events from circles entirely. i think this was done in #106 but accidentally removed/overwritten in #109.

**Comment by lindsaycarr** [comment]
I had it working in #106 where you only moused over counties and it didn't matter how big the circle was because I turned off pointer events

**Comment by jread-usgs** [comment]
@lindsaycarr can you explain how that works to me? Just curious about the implementation. If the counties are below the circles (lower z-index), how does the pointer get recognized by the polygon under the dot?

**Comment by lindsaycarr** [comment]
Because the dot doesn't have any pointer event, so the pointer event passes right through it. This probably explains it much better - https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

> **none**
> The element is never the target of mouse events; however, mouse events may target its descendant elements if those descendants have pointer-events set to some other value. In these circumstances, mouse events will trigger event listeners on this parent element as appropriate on their way to/from the descendant during the event capture/bubble phases.

**Comment by jread-usgs** [comment]
THAT IS AWESOME! thank lcarr
