### ISSUE TITLE
Proposal for mobile zoom/pan behaviors (M)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#93]
Develop a proposal for what behaviors should be invoked by tapping, double-tapping, pinching, etc. on mobile

**Comment by mwernimont** [comment]
My thoughts on the mobile questions on this task, here https://docs.google.com/document/d/1mbNAoJB68tzEEhMaU-7gaV8Xm-ccMVn0Ebf-4htJgrA/edit

Apologies for my over the use of the word plus, apparently it's my favorite word when describing positives.  I have pictures and mockups in the google doc if that entices you to actually go read it.  I am also not a gifted writer, so if I am confusing at all in parts, ask me to clarify anything.

I would also get Mitch's opinion on the matter too though, he has much more map on mobile experience than I.  I did ask him what he's used in the past which are these 2 libraries.  http://zingchart.github.io/zingtouch/ and https://hammerjs.github.io/

**Comment by aappling-usgs** [comment]
Lots of progress on this today. Next steps are in #140. @mwernimont , got a time estimate?

**Comment by mwernimont** [comment]
Not a good one, 5-10hrs?  Depends on how smoothly things go.

**Comment by aappling-usgs** [comment]
5-10 hours is for work you've already done, right? Future work hours can go in #140.

**Comment by mwernimont** [comment]
oh, it would be around 5hrs for this one.
