### ISSUE TITLE
Darken the circle outlines

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#96]

**Comment by jread-usgs** [comment]
A starting point for this would be to use 100% opacity of the full color for the stroke and use a lesser opacity for the fill. That is what I did for the gif and I think it looks ok.

**Comment by jread-usgs** [comment]
One thing that makes this a little harder than it would seem is that the stroke width will scale with the circle, so you need to scale _down_ the stroke when the circle scales up to keep the same line width. 

Same thing goes for state borders. Easy way to see this is in Rhode Island, where we'd want the circle borders to be the same as national view and be able to limit the state border scale in the same way:
![image](https://user-images.githubusercontent.com/2349007/38063473-fdfe8976-32be-11e8-92d9-43e2236c6d8f.png)

***Actually*** this seems to be only an issue w/ zooming into the states. D3 scale seems to be smart and handle the stroke scaling itself

**Comment by aappling-usgs** [comment]
Revised the title to describe the expanded scope from jread's comments

I think there are two ways to preserve the same line widths at both national and state scales:
1) use changes to projection rather than changes to transform to do the zooming. i'm not quite sure how to do this, but it might be faster. or not?
2) scale down all the stroke widths in proportion to the scaling up from the transform. zooming happens in `updateView` [here](https://github.com/USGS-VIZLAB/water-use-15/blob/e6072cbd4e0251eefd38dd561c32351ef0254d74/js/map_utils.js#L119-L148) and [here](https://github.com/USGS-VIZLAB/water-use-15/blob/e6072cbd4e0251eefd38dd561c32351ef0254d74/js/map_utils.js#L173-L179). This approach might be faster to implement, and who knows - maybe it's actually the better performance choice, too.

**Comment by jread-usgs** [comment]
Note that two options help uw w/ stroke width on the circles: use radius scaling instead of `transform=scale(x,y)` or use `path` instead of `circle` to represent the dots

**Comment by aappling-usgs** [comment]
i think what's left in this issue is to switch from using transforms to using radius scaling. is that right? anything else? path instead of circle is in issue #119...does this issue (#96) need to wait on that one (#119) to proceed?

**Comment by jread-usgs** [comment]
If we are using paths in the end, should we skip radius scaling?

**Comment by jread-usgs** [comment]
see https://github.com/USGS-VIZLAB/water-use-15/issues/97#issuecomment-377971764 for the details, but here is an example:
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" preserveAspectRatio="xMinYMin meet" viewBox="0 0 100 100">
	<g>
		<circle r="8" stroke="black" stroke-width="0.5" fill="red" transform="translate(20,40)"/>
		<circle r="1" stroke="purple" stroke-width="0.5" fill="red" transform="translate(40,40)scale(8)"/>
		<circle r="2" stroke="black" stroke-width="0.5" fill="red" transform="translate(20,60)"/>
		<circle r="1" stroke="black" stroke-width="0.5" fill="red" transform="translate(40,60)scale(2)"/>
		<circle r="4" fill="black" transform="translate(20,80)"/>
		<circle r="1" fill="purple" transform="translate(40,80)scale(4)"/>
	</g>
</svg>
```
which creates
![image](https://user-images.githubusercontent.com/2349007/38340792-d9162836-383a-11e8-8e0b-a53a0abbde76.png)

note the two on the right w/ strokes are using `scale()` to increase the circle size, but it also scales the stroke width. When you use `r` instead (or use `path`), the stroke remains consistent regardless of the size of the circle. 

My comment above (skipping `r` scaling) is in reference to it not being worth changing the scaling the radius if we are moving to `path` elements anyhow. Even though it would be pretty quick to switch the transition from `scale()` to `r` after pulling out the coin flip.

**Comment by jread-usgs** [comment]
For completing this task, I think I am blocked by #119.

**Comment by aappling-usgs** [comment]
Spinning off the "spin all strokes on zoom" part into a different issue (#154) so that this issue can simply be to darken the circle outlines.
