### ISSUE TITLE
Add state abbreviation to county mouseover (S)

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#99]
e.g., Dane County, WI

**Comment by aappling-usgs** [comment]
probably means editing this line: https://github.com/USGS-VIZLAB/water-use-15/blob/8346af314e803fb375b677f1ce51d60986097d98/js/map_utils.js#L226 by adding the abbreviations, which I _think_ are already available right there in `d.properties.STATE_ABBV`

in chrome developer tools console:
```
> countyData.get("USA")[0].properties
{GEOID: "01005", STATE_ABBV: "AL", COUNTY: "Barbour County", countypop: 26.489, total: 9.02, …}
```
